# Generated by Django 5.2.7

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('text', models.CharField(max_length=500, verbose_name='Текст сообщения')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время отправки')),
                ('session_id', models.CharField(db_index=True, max_length=255, verbose_name='ID сессии')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-timestamp'],
                'indexes': [
                    models.Index(fields=['-timestamp'], name='api_message_timesta_idx'),
                    models.Index(fields=['session_id'], name='api_message_session_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='ID сессии')),
                ('username', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('last_activity', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Последняя активность')),
                ('last_message_time', models.DateTimeField(blank=True, null=True, verbose_name='Время последнего сообщения')),
            ],
            options={
                'verbose_name': 'Сессия пользователя',
                'verbose_name_plural': 'Сессии пользователей',
                'indexes': [
                    models.Index(fields=['session_id'], name='api_userses_session_idx'),
                    models.Index(fields=['last_activity'], name='api_userses_last_ac_idx'),
                ],
            },
        ),
    ]
